// <auto-generated />
namespace RentABook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class genrename_book : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genrename_book));
        
        string IMigrationMetadata.Id
        {
            get { return "202402161946184_genrename_book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
